import { defineConfig, moduleTools } from '@modern-js/module-tools';

export default defineConfig({
  plugins: [moduleTools()],
  testing: {
    transformer: 'ts-jest',
  },
  buildConfig: [
    {
      sourceDir: 'src/components/Article',
      input: ['./src/components/Article/index.tsx'],
      outDir: 'dist/Article',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Comment',
      input: ['./src/components/Comment/index.tsx'],
      outDir: 'dist/Comment',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Sidebar',
      input: ['./src/components/Sidebar/index.tsx'],
      outDir: 'dist/Sidebar',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Tags',
      input: ['./src/components/Tags/index.tsx'],
      outDir: 'dist/Tags',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/List',
      input: ['./src/components/List/index.tsx'],
      outDir: 'dist/List',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Paging',
      input: ['./src/components/Paging/index.tsx'],
      outDir: 'dist/Paging',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/T3',
      input: ['./src/components/T3/index.tsx'],
      outDir: 'dist/T3',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Cover',
      input: ['./src/components/Cover/index.tsx'],
      outDir: 'dist/Cover',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Protected',
      input: ['./src/components/Protected/index.tsx'],
      outDir: 'dist/Protected',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Notice',
      input: ['./src/components/Notice/index.tsx'],
      outDir: 'dist/Notice',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Page',
      input: ['./src/components/Page/index.tsx'],
      outDir: 'dist/Page',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/Guestbook',
      input: ['./src/components/Guestbook/index.tsx'],
      outDir: 'dist/Guestbook',
      sourceMap: true,
      format: 'esm',
    },
    {
      sourceDir: 'src/components/LocalLog',
      input: ['./src/components/LocalLog/index.tsx'],
      outDir: 'dist/LocalLog',
      sourceMap: true,
      format: 'esm',
    },
  ],
});
